### ISSUE TITLE
envs

### ISSUE THREAD

**Issue by chengyalong123** [YBZh/DMN#1]
Thank you very much for the source code you can provide, and I would appreciate it if you could provide the virtual environment that the project requires

**Comment by YBZh** [comment]
Thanks for your interest. Our code is based on [CoOp/CoCoOp](https://github.com/KaiyangZhou/CoOp) and [TPT](https://github.com/azshue/TPT/tree/main) . Please refer to these excellent codebases for the environment.

**Comment by chengyalong123** [comment]
thank you for your answer

> Thanks for your interest. Our code is based on [CoOp/CoCoOp](https://github.com/KaiyangZhou/CoOp) and [TPT](https://github.com/azshue/TPT/tree/main) . Please refer to these excellent codebases for the environment.
